---
title: "Reaction Activity Plot"
output: html_notebook
---

# Summary
This notebook makes a reaction activity plot.

# 1. Load libraries

```{r}
library(ggplot2)
library(tidyverse)
library(grid)
library(gridExtra)
```

# 2. Load data
The data consists of the log2 fold changes for each time transition (day 7/ day 0; day 14/ day7; day 21/ day14).
```{r}
filepath = "D:/Analysis/Immune/neutrophil_foldchange.csv"
df = read_csv(filepath, col_names=FALSE)

id_path = "D:/Analysis/Immune/foldchange_ids.csv"
ids = read_csv(id_path, col_names=FALSE)

label_path = "D:/Analysis/Immune/foldchange_labels.csv"
row_labels = read_csv(label_path, col_names=FALSE)

colnames(df) = ids$X1
df$id = row_labels$X1
```

# 3. Create histograms
```{r}
drsa = reshape2::melt(df, id.vars="id")
rm(list=c('df', 'ids', 'row_labels'))

drsa$id = factor(drsa$id, levels=c("Day 7 / Day 0",
                                 "Day 14 / Day 7",
                                 "Day 21 / Day 14"))
```

```{r, fig.height=4, fig.width=6}
# Create histogram of reaction distribution
p1 = ggplot(drsa, aes(x=value, fill=id)) +
  geom_histogram(bins=100, show.legend=TRUE) +
  scale_y_log10() +
  theme_minimal() +
  xlim(-0.5, 0.5) +
  theme(plot.title = element_text(size=10),
              legend.text=element_text(size=8),
              axis.title.x=element_text(size=10),
              axis.title.y=element_text(size=10),
              axis.text.x=element_blank(),
              axis.text.y=element_text(size=8),
              legend.box="vertical",
              legend.margin=margin()) +
  labs(title="Neutrophil metabolic flux fold-change distribution",
       x=element_blank(),
       y="Number of reactions") + 
  scale_fill_manual("Fold Change", 
                    values=c("Day 7 / Day 0" = "#63ACBE", 
                             "Day 14 / Day 7" = "#601A4A", 
                             "Day 21 / Day 14" = "#EE442F"),
                    labels=c("Day 7 / Day 0",
                             "Day 14 / Day 7",
                             "Day 21 / Day 14")) 
p1
```

```{r, fig.height=2, fig.width=6}
# Create scatter plot distribution for each fold change + a little jitter
idx = sample(1:nrow(drsa), replace=FALSE)
idx = idx[1:2000]

tmp = data.frame(cbind(drsa$value[idx], as.character(drsa$id[idx])))
tmp$X1 = as.numeric(tmp$X1)
tmp$X2 = factor(tmp$X2, levels=c("Day 21 / Day 14",
                                 "Day 14 / Day 7",
                                 "Day 7 / Day 0"))
p2 = ggplot(tmp, aes(x=X1, y=X2, color=X2)) +
     geom_point(show.legend=FALSE) +
     geom_jitter() +
     theme_minimal() + 
     theme(legend.position="none") +
     xlim(-0.5, 0.5) +
     labs(x=expression(Log[2]~(fold~change)~distribution),
          y=element_blank()) + 
     scale_color_manual(values=c("Day 7 / Day 0" = "#63ACBE", 
                                 "Day 14 / Day 7" = "#601A4A", 
                                 "Day 21 / Day 14" = "#EE442F")) 
p2
```


```{r}
# Arrange the two plots
aln_plt = cowplot::align_plots(p1, p2, align="v")

cowplot::plot_grid(aln_plt[[1]], aln_plt[[2]], ncol=1, align='v')

cowplot::plot_grid(p1, p2, ncol=1, align='v')
```
